"""Initial migration with structured models.

Revision ID: 5dd082a1d1ee
Revises: 
Create Date: 2025-08-21 11:37:10.509935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dd082a1d1ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_box',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('denomination',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('cash_box_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cash_box_id'], ['cash_box.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_table('movement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('movement_type', sa.String(length=50), nullable=False),
    sa.Column('origin', sa.String(length=50), nullable=False),
    sa.Column('cash_box_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cash_box_id'], ['cash_box.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movement')
    op.drop_table('denomination')
    op.drop_table('cash_box')
    # ### end Alembic commands ###
